config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'pdf/generate_pdf'

  mount Sidekiq::Web => '/sidekiq'

  devise_for :users
  resources :friends

  get 'posts/download_all_pdf', to: 'posts#download_all_pdf', as: 'download_all_pdf'

  resources :posts do
    resources :comments, only: [:create]

    member do
      get :download_pdf
      post :generate_pdf
    end
    collection do
      post :generate_all_pdf
    end
  end

  get 'home/about'
  root 'home#index'
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    get 'comments/index'
    get 'comments/destroy'
    get 'posts/index'
    resources :posts do
      resources :comments, only: [:index, :destroy]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user, optional: true

  validates :body, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post
  before_action :set_comment, only: [:destroy]

  def index
    authorize [:admin, Comment]
    @comments = @post.comments
  end

  def destroy
    authorize [:admin, @comment]
    @comment.destroy
    redirect_to admin_post_comments_path(@post), notice: "Komentarz usunięty."
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  #before_action :authenticate_user!, only: [:create]

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user if user_signed_in?

    if @comment.save
      redirect_to @post, notice: "Komentarz dodany."
    else
      redirect_to @post, alert: "Komentarz nie został dodany."
    end
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/destroy.html.erb
<h1>Admin::Comments#destroy</h1>
<p>Find me in app/views/admin/comments/destroy.html.erb</p>

app/views/admin/comments/index.html.erb
<h2>Komentarze do posta: <%= @post.title %></h2>
<% @comments.each do |comment| %>
  <div class="border p-2 mb-2">
    <p><%= comment.body %></p>
    <%= button_to "Usuń", admin_post_comment_path(@post, comment),
                  method: :delete,
                  data: { turbo_confirm: "Na pewno usunąć?" },
                  class: "btn btn-danger btn-sm" %>
  </div>
<% end %>