config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'pdf/generate_pdf'

  mount Sidekiq::Web => '/sidekiq'

  devise_for :users
  resources :friends

  get 'posts/download_all_pdf', to: 'posts#download_all_pdf', as: 'download_all_pdf'

  resources :posts do
    resources :comments, only: [:create]

    member do
      get :download_pdf
      post :generate_pdf
    end
    collection do
      post :generate_all_pdf
    end
  end

  get 'home/about'
  root 'home#index'
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    get 'comments/index'
    get 'comments/destroy'
    get 'posts/index'
    resources :posts do
      resources :comments, only: [:index, :destroy]
    end
  end
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h4>
      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.text_field :first_name, class: "form-control", placeholder: "First Name" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
  </div>

  <div class="mb-3">
    <%= form.email_field :email, class: "form-control", placeholder: "Email" %>
  </div>

  <div class="mb-3">
    <%= form.telephone_field :phone, class: "form-control", placeholder: "Phone" %>
  </div>

  <div class="mb-3">
    <%= form.text_field :twitter, class: "form-control", placeholder: "Twitter" %>
  </div>

  <%= form.submit class: 'btn btn-secondary' %>
<% end %>

app/views/friends/_friend.html.erb
<!--<div id="<%#= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%#= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%#= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%#= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%#= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%#= friend.twitter %>
  </p>

</div>-->

app/views/friends/edit.html.erb
<h1>Editing friend</h1>
<br/>
<%= render "form", friend: @friend %>

<br/>
  <%= link_to "Show this friend", @friend, class:"btn btn-secondary"%>
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>

app/views/friends/index.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Twitter</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @friends.each do |friend| %>
    <tr>
      <td><%= friend.first_name %></td>
      <td><%= friend.last_name %></td>
      <td><%= friend.email %></td>
      <td><%= friend.phone %></td>
      <td><%= friend.twitter %></td>
      <td><%= link_to 'Show', friend %></td>
      <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
      <td><%= link_to 'Destroy', friend, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>
<br/>
<%= render "form", friend: @friend %>
<br/>
<%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>

app/views/friends/show.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">
      <%= @friend.first_name %>
      <%= @friend.last_name %>
    </h1>
    <p class="col-md-8 fs-4">
      <%= @friend.email %> |
      <%= @friend.phone %> |
      <%= @friend.twitter %>
    </p>
    <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary" %>
    <%= link_to "Back to friends", friends_path, class:"btn btn-secondary" %>
  </div>
</div>

</p>

<%= render @friend %>