config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'pdf/generate_pdf'

  mount Sidekiq::Web => '/sidekiq'

  devise_for :users
  resources :friends

  get 'posts/download_all_pdf', to: 'posts#download_all_pdf', as: 'download_all_pdf'

  resources :posts do
    resources :comments, only: [:create]

    member do
      get :download_pdf
      post :generate_pdf
    end
    collection do
      post :generate_all_pdf
    end
  end

  get 'home/about'
  root 'home#index'
  get "up" => "rails/health#show", as: :rails_health_check

  namespace :admin do
    get 'comments/index'
    get 'comments/destroy'
    get 'posts/index'
    resources :posts do
      resources :comments, only: [:index, :destroy]
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%=link_to "About Us", home_about_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%=link_to "Friends", friends_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Posts", posts_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to "Panel Admina", admin_posts_path, class: "nav-link text-warning fw-bold" %>
            </li>
          <% end %>
          <li class="nav-item">
            <%=link_to "Add a Friend", new_friend_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Add Post", new_post_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%=link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%=link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%=link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <%end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Abouts us...</h1>
<h5>Phasellus quis dui sed urna auctor vehicula vitae ac purus.
  Sed in sapien sed purus gravida volutpat id quis metus.
  Praesent facilisis quam venenatis, tincidunt libero id, efficitur mi.
  Nunc vel nulla vitae sapien semper rhoncus sit amet ac velit.
  Fusce tempus euismod nisi, sit amet euismod libero mollis eget.</h5>

admin@example.com
password

app/views/home/index.html.erb
<h1>Witaj na blogu!</h1>

<%= link_to 'Zobacz posty', posts_path, class: 'btn btn-primary' %>

<% if user_signed_in? %>
  <%= link_to 'Dodaj nowy post', new_post_path, class: 'btn btn-success' %>
<% else %>
  <p><%= link_to 'Zaloguj się', new_user_session_path %>, żeby dodawać posty.</p>
<% end %>